In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.listdir('data')

['.ipynb_checkpoints',
 'Bike_Data.xlsx',
 'car data.csv',
 'car.csv',
 'config.ini',
 'Custumer_Data.xlsx',
 'EmployeeDataToClean.xlsx',
 'Emp_Training_Data.xlsx',
 'investment_banking.xlsx',
 'Orders_Data.xlsx',
 'Orders_Data_2.xlsx',
 'superstore.xlsx',
 't_file.txt']

In [3]:
data = pd.read_excel('data/investment_banking.xlsx')

In [132]:
df = data.copy()

In [133]:
df.columns

Index(['broker_id', 'city', 'broker_type', 'fund_category', 'email_opened',
       'webex_meet', 'sales_call', 'firm_sales', 'global_sales'],
      dtype='object')

In [134]:
df.shape

(753089, 9)

In [135]:
df.head(2)

broker_id            city          broker_type  \
0    BRXX-1  PLANTATION, FL  Inter-dealer broker   
1    BRXX-1    BRANFORD, CT  Inter-dealer broker   

                          fund_category email_opened webex_meet sales_call  \
0  Emerging-Markets Local-Currency Bond          NaN        NaN        NaN   
1                             Utilities          NaN        NaN        NaN   

   firm_sales  global_sales  
0      174.62        174.62  
1        0.00          0.00

In [136]:
df.broker_id.nunique()

1178

In [137]:
df.isna().sum()

broker_id             0
city                  0
broker_type           0
fund_category         0
email_opened     434545
webex_meet       667429
sales_call       573091
firm_sales            0
global_sales          0
dtype: int64

In [138]:
df.webex_meet.unique()

array([nan, 'Y'], dtype=object)

In [139]:
df['email_opened'].unique()

array([nan, 'Y'], dtype=object)

In [140]:
df['sales_call'].unique()

array([nan, 'Y'], dtype=object)

In [141]:
df['email_opened'] = df['email_opened'].fillna('N')

In [142]:
df['sales_call'] = df['sales_call'].fillna('N')

In [143]:
df['webex_meet'] = df['webex_meet'].fillna('N')

In [144]:
df.broker_type.unique()

array(['Inter-dealer broker', 'full-service broker'], dtype=object)

In [145]:
df.broker_type.value_counts()

broker_type
Inter-dealer broker    696949
full-service broker     56140
Name: count, dtype: int64

In [146]:
#select count(distinct broker_id),broker_type from df group by broker_type
df.groupby(df['broker_type'])['broker_id'].nunique()

broker_type
Inter-dealer broker    1173
full-service broker       5
Name: broker_id, dtype: int64

In [147]:
df.isna().sum()

broker_id        0
city             0
broker_type      0
fund_category    0
email_opened     0
webex_meet       0
sales_call       0
firm_sales       0
global_sales     0
dtype: int64

In [148]:
df.head(2)

broker_id            city          broker_type  \
0    BRXX-1  PLANTATION, FL  Inter-dealer broker   
1    BRXX-1    BRANFORD, CT  Inter-dealer broker   

                          fund_category email_opened webex_meet sales_call  \
0  Emerging-Markets Local-Currency Bond            N          N          N   
1                             Utilities            N          N          N   

   firm_sales  global_sales  
0      174.62        174.62  
1        0.00          0.00

In [149]:
stat = df.city.str[-2:]
citi = df.city.str[:-4]

In [150]:
df['state'] = df['city'].str.split(',',expand = True)[1]

In [151]:
df['city'] = df['city'].str.split(',',expand = True)[0]

In [152]:
df.head()

broker_id           city          broker_type  \
0    BRXX-1     PLANTATION  Inter-dealer broker   
1    BRXX-1       BRANFORD  Inter-dealer broker   
2    BRXX-1      JONESBORO  Inter-dealer broker   
3    BRXX-2         VIENNA  Inter-dealer broker   
4    BRXX-3  CHAGRIN FALLS  full-service broker   

                          fund_category email_opened webex_meet sales_call  \
0  Emerging-Markets Local-Currency Bond            N          N          N   
1                             Utilities            N          N          N   
2               Intermediate Government            N          N          N   
3               Intermediate Government            Y          N          N   
4                      Target-Date 2050            Y          N          Y   

   firm_sales  global_sales state  
0      174.62        174.62    FL  
1        0.00          0.00    CT  
2        0.00          0.00    GA  
3        0.00      30709.00    VA  
4        0.00          0.00    OH

In [156]:
df1 = df[['broker_id','firm_sales']]
broker_firm_sales = df1.groupby('broker_id',as_index=False).sum()
broker_firm_sales.head()

broker_id   firm_sales
0     BRXX-1  11157673.73
1    BRXX-10         0.00
2   BRXX-100    267918.14
3  BRXX-1000         0.00
4  BRXX-1001         0.00

In [158]:
df2 = df[['broker_id','global_sales']]
broker_global_sales = df2.groupby('broker_id',as_index=False).sum()
broker_global_sales.head()

broker_id  global_sales
0     BRXX-1  1.066317e+08
1    BRXX-10  7.483650e+05
2   BRXX-100  8.150361e+06
3  BRXX-1000  0.000000e+00
4  BRXX-1001  1.089745e+06

In [168]:
del data
del stat
del citi

In [169]:
import gc
collected = gc.collect()
print("Garbage collector: collected",
          "%d objects." % collected)

Garbage collector: collected 2962 objects.


In [173]:
df1.merge(df2, how='inner')

MemoryError: Unable to allocate 139. GiB for an array with shape (18713020829,) and data type int64

In [164]:
df1.broker_id = df1.broker_id.astype(str)
df2.broker_id = df2.broker_id.astype(str)
# df1.merge(df2, on='broker_id',how='inner')

C:\Users\Computer\AppData\Local\Temp\ipykernel_16160\3590492922.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.broker_id = df1.broker_id.astype(str)
C:\Users\Computer\AppData\Local\Temp\ipykernel_16160\3590492922.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.broker_id = df2.broker_id.astype(str)


In [6]:
class Broker:
    def __init__(self):
        pass
    

In [7]:
class Bank:
    def __init__(self):
        pass