In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.listdir('data')

['.ipynb_checkpoints',
 'Bike_Data.xlsx',
 'car data.csv',
 'car.csv',
 'config.ini',
 'Custumer_Data.xlsx',
 'EmployeeDataToClean.xlsx',
 'Emp_Training_Data.xlsx',
 'investment_banking.xlsx',
 'Orders_Data.xlsx',
 'Orders_Data_2.xlsx',
 'superstore.xlsx',
 't_file.txt']

In [3]:
data = pd.read_excel('data/investment_banking.xlsx')

In [132]:
df = data.copy()

In [133]:
df.columns

Index(['broker_id', 'city', 'broker_type', 'fund_category', 'email_opened',
       'webex_meet', 'sales_call', 'firm_sales', 'global_sales'],
      dtype='object')

In [134]:
df.shape

(753089, 9)

In [135]:
df.head(2)

broker_id            city          broker_type  \
0    BRXX-1  PLANTATION, FL  Inter-dealer broker   
1    BRXX-1    BRANFORD, CT  Inter-dealer broker   

                          fund_category email_opened webex_meet sales_call  \
0  Emerging-Markets Local-Currency Bond          NaN        NaN        NaN   
1                             Utilities          NaN        NaN        NaN   

   firm_sales  global_sales  
0      174.62        174.62  
1        0.00          0.00

In [136]:
df.broker_id.nunique()

1178

In [137]:
df.isna().sum()

broker_id             0
city                  0
broker_type           0
fund_category         0
email_opened     434545
webex_meet       667429
sales_call       573091
firm_sales            0
global_sales          0
dtype: int64

In [138]:
df.webex_meet.unique()

array([nan, 'Y'], dtype=object)

In [139]:
df['email_opened'].unique()

array([nan, 'Y'], dtype=object)

In [140]:
df['sales_call'].unique()

array([nan, 'Y'], dtype=object)

In [141]:
df['email_opened'] = df['email_opened'].fillna('N')

In [142]:
df['sales_call'] = df['sales_call'].fillna('N')

In [143]:
df['webex_meet'] = df['webex_meet'].fillna('N')

In [144]:
df.broker_type.unique()

array(['Inter-dealer broker', 'full-service broker'], dtype=object)

In [145]:
df.broker_type.value_counts()

broker_type
Inter-dealer broker    696949
full-service broker     56140
Name: count, dtype: int64

In [146]:
#select count(distinct broker_id),broker_type from df group by broker_type
df.groupby(df['broker_type'])['broker_id'].nunique()

broker_type
Inter-dealer broker    1173
full-service broker       5
Name: broker_id, dtype: int64

In [147]:
df.isna().sum()

broker_id        0
city             0
broker_type      0
fund_category    0
email_opened     0
webex_meet       0
sales_call       0
firm_sales       0
global_sales     0
dtype: int64

In [148]:
df.head(2)

broker_id            city          broker_type  \
0    BRXX-1  PLANTATION, FL  Inter-dealer broker   
1    BRXX-1    BRANFORD, CT  Inter-dealer broker   

                          fund_category email_opened webex_meet sales_call  \
0  Emerging-Markets Local-Currency Bond            N          N          N   
1                             Utilities            N          N          N   

   firm_sales  global_sales  
0      174.62        174.62  
1        0.00          0.00

In [149]:
stat = df.city.str[-2:]
citi = df.city.str[:-4]

In [150]:
df['state'] = df['city'].str.split(',',expand = True)[1]

In [151]:
df['city'] = df['city'].str.split(',',expand = True)[0]

In [214]:
df[df['state'].str.len()>2]

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [215]:
df['state'].str.isnumeric().sum()

0

In [216]:
df['city'].str.isnumeric().sum()

37

In [221]:
df[df['city'].str.isnumeric()]['city'].unique()

array(['64150', '15801', '95678'], dtype=object)

In [222]:
df['city'] = df['city'].replace({'64150': 'Riverside','15801': 'Pennsylvania', '95678': 'Roseville' })

In [224]:
df['city'].str.isnumeric().sum()

0

In [210]:
cit = pd.DataFrame()

In [217]:
# cit[['city','state']] = df['city'].str.split(',',expand = True, n=1)

In [212]:
cit.head(2)

Empty DataFrame
Columns: []
Index: []

In [152]:
df.head()

broker_id           city          broker_type  \
0    BRXX-1     PLANTATION  Inter-dealer broker   
1    BRXX-1       BRANFORD  Inter-dealer broker   
2    BRXX-1      JONESBORO  Inter-dealer broker   
3    BRXX-2         VIENNA  Inter-dealer broker   
4    BRXX-3  CHAGRIN FALLS  full-service broker   

                          fund_category email_opened webex_meet sales_call  \
0  Emerging-Markets Local-Currency Bond            N          N          N   
1                             Utilities            N          N          N   
2               Intermediate Government            N          N          N   
3               Intermediate Government            Y          N          N   
4                      Target-Date 2050            Y          N          Y   

   firm_sales  global_sales state  
0      174.62        174.62    FL  
1        0.00          0.00    CT  
2        0.00          0.00    GA  
3        0.00      30709.00    VA  
4        0.00          0.00    OH

In [230]:
df1 = df[['broker_id','firm_sales','global_sales']]
broker_firm_sales = df1.groupby('broker_id', as_index=False).sum()
broker_firm_sales.head()

broker_id   firm_sales  global_sales
0     BRXX-1  11157673.73  1.066317e+08
1    BRXX-10         0.00  7.483650e+05
2   BRXX-100    267918.14  8.150361e+06
3  BRXX-1000         0.00  0.000000e+00
4  BRXX-1001         0.00  1.089745e+06

In [229]:
broker_firm_sales.shape

(1178, 2)

In [179]:
del df1
del df2

In [168]:
del data
del stat
del citi

In [169]:
import gc
collected = gc.collect()
print("Garbage collector: collected",
          "%d objects." % collected)

Garbage collector: collected 2962 objects.


In [177]:
df1.shape

(753089, 2)

In [176]:
df2.shape

(753089, 2)

In [239]:
report['firm_sales'] = report['firm_sales'].astype('int64')
report['global_sales'] = report['global_sales'].astype('int64')
report['loyalty_percent'] = (report['firm_sales']/report['global_sales'])*100
report.head()

broker_id  firm_sales  global_sales  loyalty_percent  \
0     BRXX-1    11157673     106631687        10.463750   
1    BRXX-10           0        748365         0.000000   
2   BRXX-100      267918       8150360         3.287192   
3  BRXX-1000           0             0              NaN   
4  BRXX-1001           0       1089745         0.000000   

         loyalty_category  
0  Less Inclinded Brokers  
1    Non Comitted Brokers  
2  Less Inclinded Brokers  
3        Stagnant Brokers  
4    Non Comitted Brokers

In [240]:
report[report['loyalty_percent']==100]

broker_id  firm_sales  global_sales  loyalty_percent loyalty_category
8    BRXX-1005          77            77            100.0    Loyal Brokers
23   BRXX-1019        5571          5571            100.0    Loyal Brokers
42   BRXX-1036         245           245            100.0    Loyal Brokers
621   BRXX-498       13042         13042            100.0    Loyal Brokers

In [241]:
def loyalty_check(l_percent):
    if l_percent == 100:
        return "Loyal Brokers"
    elif l_percent >= 85:
        return "Steadyfast Brokers"
    elif l_percent == 0:
        return "Non Comitted Brokers"
    elif l_percent <= 50:
        return "Less Inclinded Brokers"
    elif l_percent <85:
        return "Reasonably Devoted Brokers(Moderate)"
    else:
        return "Stagnant Brokers"

In [242]:
report['loyalty_category'] = report['loyalty_percent'].apply(loyalty_check)

In [245]:
report[['loyalty_category','broker_id']].groupby('loyalty_category',as_index=False).count()

loyalty_category  broker_id
0                Less Inclinded Brokers        310
1                         Loyal Brokers          4
2                  Non Comitted Brokers        686
3  Reasonably Devoted Brokers(Moderate)          7
4                      Stagnant Brokers        166
5                    Steadyfast Brokers          5

In [256]:
report[['loyalty_category','broker_id']].groupby('loyalty_category',as_index=False).nunique()

loyalty_category  broker_id
0                Less Inclinded Brokers        310
1                         Loyal Brokers          4
2                  Non Comitted Brokers        686
3  Reasonably Devoted Brokers(Moderate)          7
4                      Stagnant Brokers        166
5                    Steadyfast Brokers          5

In [246]:
report

broker_id  firm_sales  global_sales  loyalty_percent  \
0        BRXX-1    11157673     106631687        10.463750   
1       BRXX-10           0        748365         0.000000   
2      BRXX-100      267918       8150360         3.287192   
3     BRXX-1000           0             0              NaN   
4     BRXX-1001           0       1089745         0.000000   
...         ...         ...           ...              ...   
1173   BRXX-995           0         18126         0.000000   
1174   BRXX-996           0         31967         0.000000   
1175   BRXX-997           0        165500         0.000000   
1176   BRXX-998           0             0              NaN   
1177   BRXX-999           0         12870         0.000000   

            loyalty_category  
0     Less Inclinded Brokers  
1       Non Comitted Brokers  
2     Less Inclinded Brokers  
3           Stagnant Brokers  
4       Non Comitted Brokers  
...                      ...  
1173    Non Comitted Brokers  
1174    Non Comitted Brokers  
1175    Non Comitted Brokers  
1176        Stagnant Brokers  
1177    Non Comitted Brokers  

[1178 rows x 5 columns]

In [257]:
df1 = df.merge(report[['broker_id','loyalty_category']],how='inner',on='broker_id')
df1.head(2)

broker_id        city          broker_type  \
0    BRXX-1  PLANTATION  Inter-dealer broker   
1    BRXX-1    BRANFORD  Inter-dealer broker   

                          fund_category email_opened webex_meet sales_call  \
0  Emerging-Markets Local-Currency Bond            N          N          N   
1                             Utilities            N          N          N   

   firm_sales  global_sales state        loyalty_category  
0      174.62        174.62    FL  Less Inclinded Brokers  
1        0.00          0.00    CT  Less Inclinded Brokers

In [258]:
df1.shape

(753089, 11)

In [259]:
df1[['broker_id','email_opened','loyalty_category']].groupby(['email_opened','loyalty_category']).nunique()

broker_id
email_opened loyalty_category                               
N            Less Inclinded Brokers                      299
             Loyal Brokers                                 3
             Non Comitted Brokers                        570
             Reasonably Devoted Brokers(Moderate)          4
             Stagnant Brokers                            134
             Steadyfast Brokers                            4
Y            Less Inclinded Brokers                      291
             Loyal Brokers                                 1
             Non Comitted Brokers                        245
             Reasonably Devoted Brokers(Moderate)          6
             Stagnant Brokers                             36
             Steadyfast Brokers                            4

In [260]:
df1[['broker_id','broker_type','loyalty_category']].groupby(['broker_type','loyalty_category']).nunique()

broker_id
broker_type         loyalty_category                               
Inter-dealer broker Less Inclinded Brokers                      306
                    Loyal Brokers                                 4
                    Non Comitted Brokers                        685
                    Reasonably Devoted Brokers(Moderate)          7
                    Stagnant Brokers                            166
                    Steadyfast Brokers                            5
full-service broker Less Inclinded Brokers                        4
                    Non Comitted Brokers                          1

In [264]:
df1[['broker_id','state','loyalty_category']].groupby(['state','loyalty_category']).nunique()

broker_id
state loyalty_category                 
      Less Inclinded Brokers          4
      Non Comitted Brokers            1
AK    Less Inclinded Brokers         41
AL    Less Inclinded Brokers        108
      Non Comitted Brokers            9
...                                 ...
WI    Non Comitted Brokers           27
      Stagnant Brokers                1
WV    Less Inclinded Brokers         84
      Non Comitted Brokers            2
WY    Less Inclinded Brokers         58

[182 rows x 1 columns]

In [6]:
class Broker:
    def __init__(self):
        pass
    

In [7]:
class Bank:
    def __init__(self):
        pass